### ISSUE TITLE
Missing `build-system` section

### ISSUE THREAD

**Issue by mgorny** [trailofbits/sigstore-rekor-types#95]
Commit 96b78d4013f5e5d2177dbdad851d8a359c4c7d9c removed the `build-system` section, effectively triggering the fallback to the *legacy* `setuptools` backend. This breaks Gentoo packaging, since we strictly enforce that the legacy backend is only used for legacy packages using the `setup.py` file, and this file isn't used by `sigstore-rekor-types`. Please explicitly specify the modern setuptools backend:

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```
